from .environment_variables import EnvironmentVariables

environmentVariables = EnvironmentVariables.dictionary()

API_LOG_NAME_SERVICE = environmentVariables["API_LOG_NAME_SERVICE"]
API_LOG_NAME_APP = environmentVariables["API_LOG_NAME_APP"]
API_LOG_PREFIX_COUNTRY = environmentVariables["API_LOG_PREFIX_COUNTRY"]
API_LOG_URL = environmentVariables["API_LOG_URL"]
API_URL_BDI = f"http://{environmentVariables['API_LOG_URL']}"
BUCKET_CSV_NAME = environmentVariables["BUCKET_NAME"]
BUCKET_CSV_KEY = environmentVariables["S3_PATH"]
COLLECTION_NAME = environmentVariables["COLLECTION_NAME"]
SESSION_API_LOG = environmentVariables["SESSION_API_LOG"]
BUCKET_NAME_FUNCTIONAL_DLK = environmentVariables["BUCKET_NAME_FUNCTIONAL_DLK"]
S3_PATH_FUNCTIONAL_DLK = environmentVariables["S3_PATH_FUNCTIONAL_DLK"]
API_PAPI_PATH = environmentVariables["API_PAPI_PATH"],
API_PAPI_APIKEY = environmentVariables["API_PAPI_APIKEY"]

LIST_COLUMNS_CSV_USEFUL = ['ANIOCAMPANA', 'CODCATALOGO', 'NUMOFERTA', 'CODESTRATEGIA', 'NROPAGINA', 'NROPAGINADIGITAL',                            'TIPOCUADRE', 'ANIOCAMPANA2', 'NUMOFERTA2', 'CODESTRATEGIA2', 'NUMOFERTA_CONCURSANTE', 'CODESTRATEGIA_CONCURSANTE', 'CODCATALOGO_CONCURSANTE', 'CODPRODUCTO', 'CODCATALOGO2', 'CODTIPOOFERTA', 'UNIDADES', 'FLAGDIGITABLE',
                           'INDPADRE', 'NROGRUPO', 'ANIOCAMPANA3', 'NUMOFERTA3', 'CODESTRATEGIA3', 'CODCONDICION', 'CODCATALOGO3', 'UNIDADESCONDICION', 'RANGOINFUU', 'RANGOSUPUU', 'ANIOCAMPANA4', 'NUMOFERTA4', 'CODESTRATEGIA4', 'CODCONDICION2', 'CODPRODUCTO2', 'CODTIPOOFERTA2', 'UNIDADES2', 'FLAGDIGITABLE2', 'NROGRUPO2', 'INDPADRE2', 'FACTORREPETICION', 'LIMITEVENTA', 'LVACTIVO']
