columnsCSVTypesGeneral = {
    'CODVENTA': str, 'CODTIPOOFERTA': str, 'UNIDADES': str,
    'FLAGDIGITABLE': str, 'NROPAGINADIGITAL': str, 'TIPOCUADRE': str,
    'FACTORCUADRE': str, 'INDPADRE': str, 'NROGRUPO': str, 'CODCONDICION': str,
    'CODCATALOGO3': str, 'UNIDADESCONDICION': str, 'RANGOINFUU': str,
    'RANGOSUPUU': str, 'CODCONDICION2': str, 'CODPRODUCTO2': str,
    'CODVENTA2': str, 'CODTIPOOFERTA2': str, 'UNIDADES2': str,
    'FLAGDIGITABLE2': str, 'FACTORCUADRE2': str, 'NROGRUPO2': str,
    'INDPADRE2': str, 'PRECIOOFERTA': str, 'PRECIOVTAPROPUESTOMN': str,
    'PRECIONORMALMN': str, 'MONTOCONDICION': str, 'RANGOINFMN': str,
    'RANGOSUPMN': str, 'PRECIORANGO': str, 'PRECIOOFERTA2': str,
    'PRECIOVTAPROPUESTOMN2': str, 'PRECIONORMALMN2': str, 'TIPODESCUENTO': str,
    'VALORDESCUENTO': str, 'FACTORREPETICION': str
}

columnsCSVTypesSpecific = {
    # Nivel 1
    'ANIOCAMPANA': int, 'CODCATALOGO': int, 'NUMOFERTA': int, 'CODESTRATEGIA': int,
    'NROPAGINA': int, 'NROPAGINADIGITAL': int, 'TIPOCUADRE': int, 'ACUMULATIVO': bool,

    # Nivel 2
    'ANIOCAMPANA2': int, 'NUMOFERTA2': int, 'CODESTRATEGIA2': int, 'NUMOFERTA_CONCURSANTE': int,
    'CODESTRATEGIA_CONCURSANTE': int, 'CODCATALOGO_CONCURSANTE': int, 'CODPRODUCTO': int,
    'CODCATALOGO2': int, 'CODTIPOOFERTA': int, 'UNIDADES': int, 'FLAGDIGITABLE': int,
    'FACTORCUADRE': float, 'INDPADRE': int, 'NROGRUPO': int, 'PRECIOOFERTA': float,
    'PRECIOVTAPROPUESTOMN': float, 'PRECIONORMALMN': float, 'VALORDESCUENTO': float,
    'FACTORREPETICION': int, 'ACUMULATIVO_PRODUCTO': bool, 'LIMITEVENTA': int,

    # Nivel 3
    'ANIOCAMPANA3': int, 'NUMOFERTA3': int, 'CODESTRATEGIA3': int, 'CODCONDICION': int,
    'CODCATALOGO3': int, 'UNIDADESCONDICION': int, 'RANGOINFUU': int, 'RANGOSUPUU': int,
    'MONTOCONDICION': float, 'RANGOINFMN': float, 'RANGOSUPMN': float, 'PRECIORANGO': float,

    # Nivel 4
    'ANIOCAMPANA4': int, 'NUMOFERTA4': int, 'CODESTRATEGIA4': int, 'CODCONDICION2': int,
    'CODPRODUCTO2': int, 'CODTIPOOFERTA2': int, 'UNIDADES2': int,
    'FLAGDIGITABLE2': int, 'FACTORCUADRE2': float, 'NROGRUPO2': int, 'INDPADRE2': int,
    'PRECIOOFERTA2': float, 'PRECIOVTAPROPUESTOMN2': float, 'PRECIONORMALMN2': float
}
